import { prisma } from "./lib/prisma";
import { calculateSwissStandings, solveSwissPairings } from "./lib/tournamentLogic";

async function main() {
  const stageId = "0ac3dfbf-2389-4049-9bd0-ec8ecc9443ee"; // Swiss stage of EFL GOLD CUP #1
  const standings = await calculateSwissStandings(stageId);

  console.log("=== STANDINGS AFTER ROUND 1 ===");
  standings.forEach((st) => {
    console.log(`${st.name}: W=${st.w}, L=${st.l}, Record=${st.record}`);
  });

  const activeTeams = standings.filter((s) => s.status === "ACTIVE");
  const pairings = solveSwissPairings(activeTeams);

  console.log("\n=== PAIRINGS GENERATED BY solveSwissPairings ===");
  pairings.forEach(([t1, t2], idx) => {
    console.log(`Match ${idx + 1}: ${t1.name} (${t1.record}) vs ${t2.name} (${t2.record})`);
  });
}

main().finally(() => prisma.$disconnect());
